import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Box, Card, CardBody, Divider, Heading, HStack, Icon, Text, VStack } from "@chakra-ui/react";
import { Link as RouterLink } from "react-router-dom";
import { FiArrowRight, FiUser, FiAlertCircle, FiLock, FiCreditCard, FiMapPin } from "react-icons/fi";
const UserInformationCards = ({ uid, hasCompletedInformation }) => {
    return (_jsx(Card, { children: _jsxs(CardBody, { width: ['xs', 'md', 'lg', '2xl'], children: [_jsx(Box, { as: RouterLink, to: `/user/profile/${uid}/information`, children: _jsxs(HStack, { gap: 4, children: [_jsx(Icon, { as: FiUser, boxSize: 8 }), _jsxs(HStack, { justifyContent: 'space-between', width: '100%', children: [_jsxs(VStack, { alignItems: 'flex-start', children: [_jsx(Heading, { children: "Mis datos" }), _jsx(Text, { children: "Gestiona tu informaci\u00F3n personal" })] }), _jsxs(VStack, { alignItems: 'flex-end', gap: 2, children: [_jsx(Icon, { as: FiArrowRight, boxSize: 6 }), !hasCompletedInformation &&
                                                _jsxs(HStack, { alignItems: 'center', color: 'red.400', children: [_jsx(Text, { children: "Completar registro" }), _jsx(Icon, { as: FiAlertCircle })] })] })] })] }) }), _jsx(Divider, { my: 4 }), _jsx(Box, { as: RouterLink, to: `/user/profile/${uid}/security`, children: _jsxs(HStack, { gap: 4, children: [_jsx(Icon, { as: FiLock, boxSize: 8 }), _jsxs(HStack, { justifyContent: 'space-between', width: '100%', children: [_jsxs(VStack, { alignItems: 'flex-start', children: [_jsx(Heading, { children: "Seguridad" }), _jsx(Text, { children: "Configura la seguridad de tu cuenta" })] }), _jsxs(VStack, { alignItems: 'flex-end', gap: 2, children: [_jsx(Icon, { as: FiArrowRight, boxSize: 6 }), !hasCompletedInformation &&
                                                _jsxs(HStack, { alignItems: 'center', color: 'red.400', children: [_jsx(Text, { children: "Completar registro" }), _jsx(Icon, { as: FiAlertCircle })] })] })] })] }) }), _jsx(Divider, { my: 4 }), _jsx(Box, { as: RouterLink, to: `/user/profile/${uid}/cards`, children: _jsxs(HStack, { gap: 4, children: [_jsx(Icon, { as: FiCreditCard, boxSize: 8 }), _jsxs(HStack, { justifyContent: 'space-between', width: '100%', children: [_jsxs(VStack, { alignItems: 'flex-start', children: [_jsx(Heading, { children: "Mis tarjetas" }), _jsx(Text, { children: "Gestiona tus tarjetas" })] }), _jsxs(VStack, { alignItems: 'flex-end', gap: 2, children: [_jsx(Icon, { as: FiArrowRight, boxSize: 6 }), !hasCompletedInformation &&
                                                _jsxs(HStack, { alignItems: 'center', color: 'red.400', children: [_jsx(Text, { children: "Completar registro" }), _jsx(Icon, { as: FiAlertCircle })] })] })] })] }) }), _jsx(Divider, { my: 4 }), _jsx(Box, { as: RouterLink, to: `/user/profile/${uid}/addresses`, children: _jsxs(HStack, { gap: 4, children: [_jsx(Icon, { as: FiMapPin, boxSize: 8 }), _jsxs(HStack, { justifyContent: 'space-between', width: '100%', children: [_jsxs(VStack, { alignItems: 'flex-start', children: [_jsx(Heading, { children: "Direcciones" }), _jsx(Text, { children: "Configura tu domicilio" })] }), _jsxs(VStack, { alignItems: 'flex-end', gap: 2, children: [_jsx(Icon, { as: FiArrowRight, boxSize: 6 }), !hasCompletedInformation &&
                                                _jsxs(HStack, { alignItems: 'center', color: 'red.400', children: [_jsx(Text, { children: "Completar registro" }), _jsx(Icon, { as: FiAlertCircle })] })] })] })] }) })] }) }));
};
export default UserInformationCards;
